name: Build Snapshot

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    name: "Build For Windows"
    runs-on: windows-latest
    steps:
      - name: Set environment vars
        shell: bash
        run: |
          snapshot_slugline="-snapshot-$(date +'%Y%m%d')-${GITHUB_SHA:0:6}"
          echo "snapshot_slugline=$snapshot_slugline" >> $GITHUB_ENV
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Version check
        run: python cre8forge.py version
      - name: Install pyinstaller
        run: pip install -U pyinstaller
      - name: Run exec bundler
        shell: bash
        run: |
          bundle_path="$(scripts/run_pyinstaller.sh)"
          echo "bundle_path=$bundle_path" >> $GITHUB_ENV
      - name: Create package
        shell: bash
        run: |
          package_path="$(scripts/create_versioned_package.sh "${{ env.bundle_path }}" win)"
          echo "package_path=$package_path" >> $GITHUB_ENV
      - name: Create archive
        shell: bash
        run: |
          package_dir="$(dirname "${{ env.package_path }}")"
          package_name="$(basename "${{ env.package_path }}")"
          cd "$package_dir"
          7z a "$package_name.zip" "$package_name"
          archive_name="$package_name.zip"
          archive_path="$(pwd)/$archive_name"
          echo "archive_path=$archive_path" >> $GITHUB_ENV
          echo "archive_name=$archive_name" >> $GITHUB_ENV
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.archive_name }}
          path: dist/${{ env.archive_name }}
        
