name: Build Snapshot

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Package for Windows
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
